---
title: ClusterDE
subtitle: "a post-clustering differential expression method"
author: Carson Zhang
date: last-modified
embed-resources: true
format:
  lmu_munich-revealjs: default
---

## Outline

- Context
  - Why and when would we use this?
  - What are the problems with existing methods or analysis procedures?
- Method
  - What is ClusterDE?
  - How does it avoid the problems of other methods?
- Examples
  - How would you use ClusterDE?
- Extensions
  - Variations on the ClusterDE method

# Context

## Differential Expression

### Example of a subtitle

We can create unordered lists:

- first item 
    - A sub item

Or ordered lists

1. Ordered list first item
    1. Nested list item

Or **bold**, *italic*, or [URL](https://lmu.de) text.

# Method

## Synthetic null generation

Inline mode: $c^2 = a^2 + b^2$

Display mode: 

$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$

## Clustering

## DE analysis (hypothesis testing)

## FDR control

# Example

## Columns

We could also split content between two columns:

::: {.columns}

::: {.column width="45%"}
Left column
:::

::: {.column width="45%"}
Right column
:::

:::

<https://quarto.org/docs/presentations/revealjs/#multiple-columns>

## Code Highlighting

For continuous highlighting, use `from-to` (`6-8`).

For discontinuous highlighting, use `line1, line2, ...` (`1, 4`).

To highlight lines in a progressive manner, use `range1|range2` (`|6-8|1,4|`). 

```{.python code-line-numbers="|6-8|1,4|"}
import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

<https://quarto.org/docs/presentations/revealjs/#code-blocks>

## Enable more revealjs features

The theme is built ontop of Quarto's `revealjs` implementation. So, any [features](https://quarto.org/docs/presentations/revealjs/) of available are also usable within the theme. For example, if we wanted to incorporate the [chalkboard](https://quarto.org/docs/presentations/revealjs/presenting.html#chalkboard) feature. We would use:

```yaml
format:
  lmu_munich-revealjs: 
    chalkboard: true
```
